### ISSUE TITLE
Screenshots can be HEIF images

### ISSUE THREAD

**Issue by haykam821** [yannbertrand/macos-defaults#172]
Using the following command allows screenshots to be saved as HEIF images (`.heic` extension):

```sh
defaults write com.apple.screencapture "type" -string "heic" 
```

**Comment by elvey** [comment]
I've been using this setting for years.  Is this project semi-abandoned?  Odd that there's no update.  Or is a pull request needed? The resulting files are much smaller, with no loss in quality.  (Much more recent, evolved algorithm.  Facebook even supports HEIC uploads. (Twitter doesn't, for such tools, I used a quick action to convert to jpeg.)

**Comment by Swiss-Mac-User** [comment]
> I've been using this setting for years. Is this project semi-abandoned? Odd that there's no update.

FYI: if you want to automate this for your macOS User, I have incorporated this here using the `useScreenshotsFormat='heic'` setting:

https://github.com/Swiss-Mac-User/macOS-scripted-setup

**Comment by yannbertrand** [comment]
Please feel free to do a PR to add `heic` to the list https://macos-defaults.com/screenshots/type.html :)
