### ISSUE TITLE
Current status of this project?

### ISSUE THREAD

**Issue by i5o** [yannbertrand/macos-defaults#217]
Heyo!
I landed by "mistake" on the https://macos-defaults.com/ website, and I loved it.

I was specifically looking for screenshot commands.
Was this ever left? Is there any motivation missing behind it?

**Comment by yannbertrand** [comment]
Hi @i5o,

The project is still ongoing, I just need to find some time to work on it 🙂

**Comment by i5o** [comment]
How can we help you @yannbertrand?

**Comment by yannbertrand** [comment]
> How can we help you @yannbertrand?

Actually not much. I hope I can find some time this summer to clean the project. But thanks for asking, it's greatly appreciated!
