### ISSUE TITLE
Probable mistake in the description of the static-only command

### ISSUE THREAD

**Issue by Gudsfile** [yannbertrand/macos-defaults#259]
The page for `static-only` command or by its title "Active applications only" indicates :

- Set to true ➡️ "_Only show active apps_"
- Set to false ➡️ "_Hide inactive apps from the Dock_"

I understand what is being said but it doesn't seem clear to me.
For the default case, I think a good formulation might be: "_Show apps pinned to the dock_".

Also, I think it's good to mention that the layout of the apps in the Dock is lost when the command is used.
For example by adding "_⚠️ Beware this command empties your Dock_" in the description

What do you think about it?

**Comment by yannbertrand** [comment]
You're totally right, thanks for the alert & fix with #260
