### ISSUE TITLE
Broken link in "How do I add a command section"

### ISSUE THREAD

**Issue by hugovandevliert** [yannbertrand/macos-defaults#314]
Hi there. While browsing I noticed that the "this file" link in the [How do I add a command](https://macos-defaults.com/#🤔-how-do-i-add-a-command) section on the main page is broken. It still points to https://github.com/yannbertrand/macos-defaults/blob/main/defaults.yml, while that file no longer exists.

Maybe it makes sense to add a link to [this section](https://github.com/yannbertrand/macos-defaults#add-a-command) in the readme instead?

**Comment by yannbertrand** [comment]
Thanks for the report! It should be fixed now :)
