### ISSUE TITLE
Broken Finder search scope (?)

### ISSUE THREAD

**Issue by MariaSolOs** [yannbertrand/macos-defaults#340]
_I apologize in advance if this isn't really a bug, but just a result of my own ignorance._

I've been trying out https://macos-defaults.com/finder/fxdefaultsearchscope.html, yet I don't see any noticeable changes in the way the search is rooted. The way I've been testing it is via a terminal and `cd`-ing to a certain directory and then launching the Finder. The search always begins from "This Mac", despite me running `defaults write com.apple.finder FXDefaultSearchScope -string "SCcf"`.

Is this because I'm misunderstanding the setting, launching the Finder in an unintended way, or a bug...?

**Comment by Swiss-Mac-User** [comment]
Hey, not sure if this helps - but I am using this to set the Finder default search scope to "Current folder":

https://github.com/Swiss-Mac-User/macOS-scripted-setup/blob/2498a0e5093cc07009f83fb9bbf03e2f45f5139b/Usersettings/Finder.sh#L116

**Comment by yannbertrand** [comment]
I've just tried on a M1 Pro MacBook 2021, macOS Sonoma 14.3.1 (23D60). The command is working correctly.

Did you run `killall Finder` after the command you use? Another small difference could be the double quotes surrounding the key `"FXDefaultSearchScope"`.

By the way this config is global and not scoped depending on the current folder, so you can just open the base folder and check it out.
