### ISSUE TITLE
`Key held down behavior` link in the left menu leads to a 404 error

### ISSUE THREAD

**Issue by ShiiFu** [yannbertrand/macos-defaults#358]
In the left menu, misc section, the link `Key held down behavior` leads to a 404.

This link is not listed on index page. I don't find any related docs in the repo. 
Is it an old deleted content?

**Comment by yannbertrand** [comment]
Thanks for creating the issue! It actually moved [to the Keyboard section](https://macos-defaults.com/keyboard/applepressandholdenabled.html).

I just removed it in https://github.com/yannbertrand/macos-defaults/pull/359.
