### ISSUE TITLE
Only show active applications in Dock

### ISSUE THREAD

**Issue by yannbertrand** [yannbertrand/macos-defaults#39]
- [x] I made sure this command is not in the commands list
- [x] I searched and didn't find this command in the listed issues
- [x] I know this `defaults` command exists
- [x] I know this command works on macOS current version
- [ ] I know this command is deprecated on macOS current version

- Folder: Dock
- Command: defaults write com.apple.dock static-only -bool true && killall Dock
- Argument type (if applicable): bool
- Examples:
  - `true` enabled
  - `false` (default) disabled

**Comment by thisisommore** [comment]
Can I work on this?

**Comment by yannbertrand** [comment]
Sure!
