### ISSUE TITLE
Use Plain Text Mode as Default

### ISSUE THREAD

**Issue by yannbertrand** [yannbertrand/macos-defaults#40]
- [x] I made sure this command is not in the commands list
- [x] I searched and didn't find this command in the listed issues
- [x] I know this `defaults` command exists
- [x] I know this command works on macOS current version
- [ ] I know this command is deprecated on macOS current version

- Folder: TextEdit
- Command: `defaults write com.apple.TextEdit RichText -bool false`
- Argument type (if applicable): bool
- Examples:
  - `false` disable rich text
  - `true` (default) enable rich text

**Comment by valentinperignon** [comment]
Hey! Can I work on this? :)

**Comment by yannbertrand** [comment]
Sure! 🙂
