### ISSUE TITLE
Set Status bar digital clock output format

### ISSUE THREAD

**Issue by yannbertrand** [yannbertrand/macos-defaults#41]
- [x] I made sure this command is not in the commands list
- [x] I searched and didn't find this command in the listed issues
- [x] I know this `defaults` command exists
- [x] I know this command works on macOS current version
- [ ] I know this command is deprecated on macOS current version

- Folder: Status bar
- Command: `sudo defaults write com.apple.menuextra.clock DateFormat -string "EEE d MMM HH:mm:ss"`
- Argument type (if applicable): string
- Examples:
  - `EEE d MMM HH:mm:ss` Thu 18 Aug 23:46:18
  - `EEE h:mm:ss` Thu 11:46:18
  - `HH:mm` 23:46

See https://github.com/herrbischoff/awesome-macos-command-line#set-menu-bar-clock-output-format

**Comment by yannbertrand** [comment]
@jidicula are you interested in taking this one?

**Comment by jidicula** [comment]
@yannbertrand sure!
