### ISSUE TITLE
Flash the Status bar digital clock time separators

### ISSUE THREAD

**Issue by yannbertrand** [yannbertrand/macos-defaults#42]
- [x] I made sure this command is not in the commands list
- [x] I searched and didn't find this command in the listed issues
- [x] I know this `defaults` command exists
- [x] I know this command works on macOS current version
- [ ] I know this command is deprecated on macOS current version

- Folder: Status bar
- Command: `defaults write com.apple.menuextra.clock FlashDateSeparators -bool true`
- Argument type (if applicable): bool
- Examples:
  - `true` Flash the time separators
  - `false` (default) Do not flash

**Comment by WorkInProgress-Development** [comment]
Can I take/work on this?

**Comment by yannbertrand** [comment]
Sure, Isaac 😄 let me know if you need help!

**Comment by WorkInProgress-Development** [comment]
Issues I have with draft PR #48:
- Recordings should use a set time, for consistency between screenshots
- I don't have access to a macOS Big Sur installation to test the recording, might need to change screenshot locations based on ui redesigns
- Menu bar screenshot smaller than the 740 pixels the other images use

_Notes: This issue used the term status bar, I've used the menu bar, the name referred to in mac documentation._

On an unrelated question, do you mind if I test some of the other defaults, and then make a (single, not going to spam the repository :)) PR adding Mojave and Catalina support tags to those which need it?

**Comment by yannbertrand** [comment]
Looks great! Thanks.

- Don't bother with the set time, it's alright without it!
- I'll run the script on my side and make sure it works on my laptop (don't have a solution for different resolutions yet). It's super appreciated that you took the time to try it!
- Is that an issue? It should be alright with smaller videos 😉 

Mojave and Catalina support tags would be great as well 😄

**Comment by WorkInProgress-Development** [comment]
I attempted to run my computer at the 2015 15" MBP resolution in the hopes of it working on your laptop, I'd love to know how it went :)

**Comment by yannbertrand** [comment]
Thank you! It's live on https://macos-defaults.com/menubar/flashdateseparators.html
