### ISSUE TITLE
Add "What's the defaults command" section

### ISSUE THREAD

**Issue by tbetous** [yannbertrand/macos-defaults#47]
I thinks it would be a great idea to add a small section in order to explain in short what is the `defaults`. I though to something like that :

## What's the 'defaults' command ? 

MacOS `man` will tell you : 

> `defaults` allows users to read, write, and delete Mac OS X user defaults from a command-line shell. Mac OS X applications and other programs use the defaults system to record user preferences and other information that must be maintained when the applications aren't running (such as default font for new documents, or the position of an Info panel). Much of this information is accessible through an application's Preferences panel, but some of it isn't, such as the position of the Info panel. You can access this information with `defaults`.

In short : It allows you to change programmatically System Settings of your Mac. 🤖 ⚙️ 🔧

**Comment by yannbertrand** [comment]
Hey @tbetous, what do you think of the [What's a `defaults` command](https://macos-defaults.com/#%F0%9F%99%8B-what-s-a-defaults-command) section? 😄

**Comment by tbetous** [comment]
Oh yep ! That's pretty good, my suggestion was to add it into the Readme, but I've just noticed there is a link in the description "An up-to-date list of macOS defaults commands with demos ✨".

My bad ! You should probably close this issue 😄 !

**Comment by yannbertrand** [comment]
The GitHub readme may be not super accessible. Don't hesitate to add some info 😉 

The homepage could have a TL;DR section as well if it's too complicated!

**Comment by apexskier** [comment]
For what it's worth, I think the current block in the readme works well - https://macos-defaults.com/#🙋-what-s-a-defaults-command

**Comment by yannbertrand** [comment]
I'm closing this issue for now :)
