### ISSUE TITLE
Show seconds in the menubar clock

### ISSUE THREAD

**Issue by jidicula** [yannbertrand/macos-defaults#53]
- [x] I made sure this feature is not in the commands list
- [x] I searched and didn't find this feature request in the listed issues

I'm looking for a command that can enable the menubar clock to show seconds. I couldn't find this command anywhere else after searching, but I *think* it should be possible.

**Comment by yannbertrand** [comment]
What about #41 ? 😄

**Comment by jidicula** [comment]
> What about #41 ? 😄

Haha thanks, I think that does it 🙂. I'll close this PR.

On a side-note, I have a bunch of other configs in my [dotfiles repo](https://github.com/jidicula/dotfiles/blob/master/system_config.sh) that I don't see in the issues list yet, so I'll try to add a bunch over the coming days.

**Comment by yannbertrand** [comment]
Nice!
