### ISSUE TITLE
Save to disk (not to iCloud) by default

### ISSUE THREAD

**Issue by jidicula** [yannbertrand/macos-defaults#68]
- [x] I made sure this command is not in the commands list
- [x] I searched and didn't find this command in the listed issues
- [x] I know this `defaults` command exists
- [x] I know this command works on macOS current version
- [ ] I know this command is deprecated on macOS current version

- Folder:  NSGlobalDomain
- Command:  NSDocumentSaveNewDocumentsToCloud
- Argument type (if applicable):  bool
- Examples:
  -  true (default): iCloud Documents is the default directory opened in the fileviewer dialog when saving a new document
  -  false: home directory is opened in the fileviewer dialog when saving a new document

**Comment by jidicula** [comment]
@yannbertrand could you assign this to me?

**Comment by jidicula** [comment]
Also, I'm not sure which folder this should go in – does it belong in Finder since the file-save dialog is essentially a Finder window?

**Comment by yannbertrand** [comment]
I'd say Finder 😉
